spring:
  application:
    name: resume_tailor

  datasource:
    url: jdbc:postgresql://localhost:5433/resume_tailor
    username: user
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

mybatis:
  configuration:
    map-underscore-to-camel-case: true

ai:
  pricing:
    input-per-million: 0.75
    output-per-million: 4.50
